import pandas as pd


def check_name(df: pd.DataFrame) -> None:
    """Check for each calendar if activity is one of the list."""
    act_names = {
        "Commute": [
            "Bike",
            "Bus",
            "Car",
            "Train",
            "Walk",
        ],
        "Chores": [
            "Clean",
            "Organization",
            "Preparation",
            "Shop",
            "Tidy up",
        ],
        "Eat": [
            "Breakfast",
            "Lunch",
            "Dinner",
        ],
        "Entertainment": [
            "Cinema",
            "Game",
            "Gaming",
            "Movie",
            "TV",
            "Twitch",
            "YouTube",
        ],
        "Personal care": [
            "Hair cut",
            "Preparation",
            "Shower",
        ],
        "Personal development": [
            "AI Challenge",
            "AI challenge",
            "AI for innovation",
            "Account management",
            "Android",
            "Article Calendar analyzer",
            "Biblioteca bot",
            "Bitwarden",
            "CV",
            "Calendar analyzer",
            "CalendarAnalyzer",
            "Computer setup",
            "Cyber challenge",
            "Data visualization",
            "Django",
            "Docker",
            "Economy",
            "Encoding",
            "FBK",
            "Firebase",
            "Firefox organization",
            "Fix PC",
            "Fix computer",
            "Git",
            "Google Collab",
            "Google Look Inside enrolment",
            "Heroku",
            "ICT days",
            "IPA alphabet",
            "Icloud contact support",
            "Internet Archive Updater",
            "Invest",
            "Investment",
            "Lean",
            "Learn",
            "Leetcode",
            "Linux",
            "Linux scripts",
            "MPM Bot",
            "MPM bot",
            "Machine learning",
            "Markdown",
            "Organization",
            "Phone analytics",
            "Phone modding",
            "Podcast",
            "Project UnitnCal",
            "Project docker tools",
            "Python",
            "Pytorch lightning",
            "Raspberry",
            "Read",
            "SOI",
            "Samsung innovation",
            "School of innovation",
            "Security keys",
            "Seminar machine learning",
            "Simple Wikipedia",
            "Speck and tech",
            "Talk",
            "Trading",
            "Twilio",
            "Ublock",
            "Ublock filters",
            "Unitn autologin",
            "Update computer",
            "Wathsapp analyzer",
            "Website",
            "Widows",
            "Windows",
            "Windows setup",
            "Workshop",
        ],
        "Spare time": [
            "Account management",
            "Apply film wrap",
            "Bike",
            "Call Susanna",
            "Car",
            "Chat",
            "Computer",
            "Donate blood",
            "Email",
            "Form graduation Luca",
            "Hacktoberfest",
            "Kidney",
            "Linux",
            "Listen Pietro laurea",
            "Manage pictures",
            "Memories",
            "Memories management",
            "Memory management",
            "Mouse",
            "Mouse warranty",
            "Organization",
            "Phone",
            "Play",
            "Podcast",
            "Read for Alessandro",
            "Really",
            "Relax",
            "Shop",
            "Shower",
            "Sleep",
            "Talk",
            "TeamViewer",
            "Think",
            "Trip organization",
            "Wait",
            "Walk",
            "Windows",
        ],
        "Sport": [
            "Beach volleyball",
            "Bike",
            "Bus",
            "Ping pong",
            "Run",
            "Ski",
            "Train",
            "Workout",
        ],
        "Study": [
            "AI for innovation",
            "Algorithms",
            "Autonomous software agents",
            "Computer vision",
            "Data mining",
            "Database",
            "English",
            "Finance",
            "Formal languages and compilers",
            "German",
            "Human computer interaction",
            "Java",
            "Kuper",
            "Logic",
            "Machine learning",
            "Natural language understanding",
            "Networks",
            "Operative systems",
            "Physics",
            "Security",
            "Software engineering 1",
            "Software engineering 2",
            "Thesis",
            "Web",
        ],
    }

    for cal, acts in act_names.items():
        df.loc[
            (df["Calendar"] == cal) & (~df["SUMMARY"].isin(acts)), "Error"
        ] = "Act not categorized"
