name: Test and Build container
on: push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - uses: pre-commit/action@v2.0.3

  python-tests:
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r requirements.txt
      - name: Run dashboard
        env:
          CALENDAR_LINKS: ${{ secrets.CALENDAR_LINKS }}
        run: |
          python app.py

  docker-build:
    needs: python-tests
    runs-on: ubuntu-latest
    steps:
      - name: PrepareReg Names
        run: echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Install buildx support for multiple architectures (e.g. arm/v7)
        run: docker run --privileged --rm tonistiigi/binfmt --install all

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ghcr.io/${{ env.IMAGE_REPOSITORY }}:latest
          platforms: |
            linux/arm64
          # linux/arm/v7 # does not install matplotlib, just buffers until timeout
          cache-from: type=gha
          cache-to: type=gha,mode=max
